"""Idempotently seed hospitals around Rajalakshmi Engineering College for demos."""

import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import select

from app.core.database import AsyncSessionLocal
from app.models.hospital import Hospital


# Coordinates are centered on Rajalakshmi Engineering College, Thandalam.
# Details are limited to public directory / hospital website information; no
# crowd-sourced ratings or inferred bed counts are included.
DEMO_HOSPITALS = [
    {
        "google_place_id": "thandalam_demo_saveetha_medical_college_hospital",
        "hospital_name": "Saveetha Medical College Hospital",
        "address": "Saveetha Nagar, Thandalam, Chennai - 602105",
        "city": "Thandalam",
        "state": "Tamil Nadu",
        "latitude": 13.0270,
        "longitude": 80.0165,
        "phone": "+91 44 6672 6617",
        "website": "https://www.saveetha.com",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=13.0270,80.0165",
        "rating": None,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Multi-specialty Care, Emergency Services, ICU, NICU, PICU, CCU, 24/7 Emergency",
        "has_emergency_room": True,
        "opening_hours": "24-hour emergency services; outpatient clinics 8:00 AM-8:00 PM daily",
        "beds": 1200,
    },
    {
        "google_place_id": "thandalam_demo_annaii_medical_college_hospital",
        "hospital_name": "Annaii Medical College and Hospital (Pennalur)",
        "address": "Pennalur, Sriperumbudur Taluk, Kanchipuram District - 602117",
        "city": "Pennalur",
        "state": "Tamil Nadu",
        "latitude": 12.9708,
        "longitude": 79.9760,
        "phone": "+91 99943 66777",
        "website": "https://annaiimedicalcollege.edu.in",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=12.9799,79.9811",
        "rating": None,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Multi-specialty Care, Radiology, MRI, CT, Emergency Services",
        "has_emergency_room": True,
        "opening_hours": "24/7 emergency services; OPD 8:00 AM-8:00 PM daily",
        "beds": 900,
    },
    {
        "google_place_id": "thandalam_demo_government_hospital_sriperumbudur",
        "hospital_name": "Government Hospital, Sriperumbudur",
        "address": "Chennai-Bangalore Highway, Sriperumbudur - 602105",
        "city": "Sriperumbudur",
        "state": "Tamil Nadu",
        "latitude": 12.957240,
        "longitude": 79.943406,
        "phone": "+91 44 2716 2250",
        "website": "https://kancheepuram.nic.in/public-utility/government-hospitalsriperumbudur/",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=12.957240,79.943406",
        "rating": None,
        "hospital_type": "Government",
        "specialties": "Accident & Emergency, Paediatrics, Ophthalmology, Dialysis",
        "has_emergency_room": True,
        "opening_hours": "Emergency services; hours not listed",
        "beds": 53,
    },
    {
        "google_place_id": "thandalam_demo_jaya_hospital_sriperumbudur",
        "hospital_name": "Jaya Hospital, Sriperumbudur",
        "address": "No. 3, Kothanda Nadar Nagar, Nenmeli, Sriperumbudur - 602105",
        "city": "Sriperumbudur",
        "state": "Tamil Nadu",
        "latitude": 12.97018,
        "longitude": 79.95207,
        "phone": "+91 98423 32443",
        "website": "https://jayahospital.com",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=12.97018,79.95207",
        "rating": None,
        "hospital_type": "Private",
        "specialties": "Multi-specialty Care, Emergency & Trauma, Orthopedics, General Surgery, Obstetrics & Gynecology, ICU, Diagnostics",
        "has_emergency_room": True,
        "opening_hours": "24 hours, 7 days a week",
        "beds": None,
    },
    {
        "google_place_id": "thandalam_demo_sri_devi_hospital",
        "hospital_name": "Sri Devi Hospital",
        "address": "No. 32, Gandhi Road, Ramanujar Nagar, Sriperumbudur - 602105",
        "city": "Sriperumbudur",
        "state": "Tamil Nadu",
        "latitude": 12.9672419,
        "longitude": 79.9456429,
        "phone": None,
        "website": None,
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=12.9672419,79.9456429",
        "rating": None,
        "hospital_type": "Private",
        "specialties": "General Hospital",
        "has_emergency_room": False,
        "opening_hours": None,
        "beds": None,
    },
    {
        "google_place_id": "thandalam_demo_pandian_hospital",
        "hospital_name": "Pandian Hospital",
        "address": "No. 19, Mahatma Gandhi Nagar, near Sriperumbudur Bus Stand, Sriperumbudur - 602105",
        "city": "Sriperumbudur",
        "state": "Tamil Nadu",
        "latitude": 12.967109,
        "longitude": 79.946791,
        "phone": "+91 44 2716 2363",
        "website": None,
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=12.967109,79.946791",
        "rating": None,
        "hospital_type": "Private",
        "specialties": "General Hospital",
        "has_emergency_room": False,
        "opening_hours": None,
        "beds": None,
    },
    {
        "google_place_id": "thandalam_demo_sri_sharada_hospital",
        "hospital_name": "Sri Sharada Hospital",
        "address": "Sriperumbudur - 602105",
        "city": "Sriperumbudur",
        "state": "Tamil Nadu",
        "latitude": 12.96727,
        "longitude": 79.9468,
        "phone": None,
        "website": None,
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=12.96727,79.9468",
        "rating": None,
        "hospital_type": "Private",
        "specialties": "General Hospital",
        "has_emergency_room": False,
        "opening_hours": None,
        "beds": None,
    },
    {
        "google_place_id": "thandalam_demo_panimalar_medical_college_hospital",
        "hospital_name": "Panimalar Medical College Hospital & Research Institute",
        "address": "Varadharajapuram, Poonamallee, Chennai - 600123",
        "city": "Poonamallee",
        "state": "Tamil Nadu",
        "latitude": 13.0567,
        "longitude": 80.0747,
        "phone": "+91 44 6161 6161",
        "website": "https://pmchri.ac.in",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=13.0567,80.0747",
        "rating": None,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Emergency Medicine, General Medicine, General Surgery, Obstetrics & Gynecology, Orthopedics, Pediatrics, Critical Care, Neurosurgery, Urology, Dialysis",
        "has_emergency_room": True,
        "opening_hours": "24-hour casualty, ambulance, blood bank, pharmacy, ICU and operating theatres",
        "beds": None,
    },
    {
        "google_place_id": "thandalam_demo_acs_medical_college_hospital",
        "hospital_name": "A.C.S. Medical College and Hospital",
        "address": "Poonamallee High Road, Velappanchavadi, Chennai - 600077",
        "city": "Velappanchavadi",
        "state": "Tamil Nadu",
        "latitude": 13.058910,
        "longitude": 80.126706,
        "phone": "+91 44 2680 2133",
        "website": "https://acsmch.ac.in",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=13.058910,80.126706",
        "rating": None,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Multi-specialty Care, Emergency Services, General & Specialty OPD, Diagnostic Services, Blood Bank",
        "has_emergency_room": True,
        "opening_hours": "Emergency services; OPD schedule not listed",
        "beds": 1115,
    },
    {
        "google_place_id": "thandalam_demo_madha_medical_college_hospital",
        "hospital_name": "Madha Medical College Hospital",
        "address": "Kundrathur Main Road, Kovur, Chennai - 600128",
        "city": "Kovur",
        "state": "Tamil Nadu",
        "latitude": 13.0040654,
        "longitude": 80.1119084,
        "phone": "+91 99400 87994",
        "website": "https://mmcri.in/hospital/",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=13.0040654,80.1119084",
        "rating": None,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Multi-specialty Care, Super-specialty Services",
        "has_emergency_room": False,
        "opening_hours": None,
        "beds": 900,
    },
    {
        "google_place_id": "thandalam_demo_sri_muthukumaran_medical_college_hospital",
        "hospital_name": "Sri Muthukumaran Medical College Hospital & Research Institute",
        "address": "Chikkarayapuram, Kundrathur Road, near Mangadu, Chennai - 600069",
        "city": "Chikkarayapuram",
        "state": "Tamil Nadu",
        "latitude": 13.0182200,
        "longitude": 80.1088730,
        "phone": "+91 44 6634 4000",
        "website": "https://smmchri.res.in",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=13.0182200,80.1088730",
        "rating": None,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Cardiology, General Medicine, General Surgery, Pediatrics, Obstetrics & Gynecology, ENT, Orthopedics, Emergency Medicine",
        "has_emergency_room": True,
        "opening_hours": "24/7 ambulance services; hospital contact: +91 44 6634 4000",
        "beds": None,
    },
    {
        "google_place_id": "thandalam_demo_kanaga_hospital",
        "hospital_name": "Kanaga Hospital",
        "address": "7-131, Kundrathur Main Road, Kovur, Mangadu, Chennai - 600128",
        "city": "Kovur",
        "state": "Tamil Nadu",
        "latitude": 13.0098614,
        "longitude": 80.1671530,
        "phone": "+91 95001 35319",
        "website": "https://kanagahospitals.com",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=13.0098614,80.1671530",
        "rating": None,
        "hospital_type": "Private",
        "specialties": "Multi-specialty Care",
        "has_emergency_room": False,
        "opening_hours": None,
        "beds": None,
    },
    {
        "google_place_id": "thandalam_demo_mehta_hospitals_global_campus",
        "hospital_name": "Dr. Mehta's Hospitals - Global Campus",
        "address": "No. 50, Poonamallee High Road, Velappanchavadi, Chennai - 600077",
        "city": "Velappanchavadi",
        "state": "Tamil Nadu",
        "latitude": 13.0617739,
        "longitude": 80.1356616,
        "phone": "+91 44 4047 4001",
        "website": "https://mehtahospital.com/velappanchavadi-campus/",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=13.0617739,80.1356616",
        "rating": None,
        "hospital_type": "Private",
        "specialties": "Cardiology, Pediatrics, Obstetrics & Gynecology, Neonatal Intensive Care, Emergency Medicine, Nephrology, Neurosurgery, Orthopedics, Gastroenterology",
        "has_emergency_room": True,
        "opening_hours": "Emergency contact: +91 44 4047 4057",
        "beds": None,
    },
    {
        "google_place_id": "thandalam_demo_sri_ramachandra_medical_centre",
        "hospital_name": "Sri Ramachandra Medical Centre",
        "address": "No. 1, Ramachandra Nagar, Porur, Chennai - 600116",
        "city": "Porur",
        "state": "Tamil Nadu",
        "latitude": 13.0380979,
        "longitude": 80.1428047,
        "phone": "+91 44 4001 2323",
        "website": "https://srmc.sriramachandra.edu",
        "google_maps_url": "https://www.google.com/maps/dir/?api=1&destination=13.0380979,80.1428047",
        "rating": None,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Cardiac Care, General Medicine, General Surgery, Pediatrics, Obstetrics & Gynecology, Orthopedics, Neurology, Neurosurgery, Nephrology, Gastroenterology, Oncology, Urology, Organ Transplant",
        "has_emergency_room": True,
        "opening_hours": "Emergency helpline: +91 44 4001 2345; appointment enquiry 8:00 AM-4:00 PM",
        "beds": 824,
    },
]


async def seed():
    async with AsyncSessionLocal() as session:
        inserted = 0
        updated = 0
        for record in DEMO_HOSPITALS:
            result = await session.execute(
                select(Hospital).where(Hospital.google_place_id == record["google_place_id"])
            )
            hospital = result.scalar_one_or_none()
            if hospital is None:
                session.add(Hospital(**record))
                inserted += 1
            else:
                for field, value in record.items():
                    setattr(hospital, field, value)
                updated += 1
        await session.commit()
    print(f"Thandalam demo catalogue saved: {inserted} inserted, {updated} updated.")


if __name__ == "__main__":
    asyncio.run(seed())
