"""
Seed curated, verified Chennai hospitals catalogue into the database.
Safe and idempotent: updates existing records or inserts new ones.
"""

import sys
import os
import uuid
import asyncio

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import select
from app.core.database import AsyncSessionLocal
from app.models.hospital import Hospital


CHENNAI_HOSPITALS = [
    # 1. Government Tertiary Care & Medical Colleges
    {
        "google_place_id": "tn_chennai_rggh",
        "hospital_name": "Rajiv Gandhi Government General Hospital (RGGGH)",
        "address": "EVR Periyar Salai, Park Town, Chennai, Tamil Nadu 600003",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0805,
        "longitude": 80.2785,
        "phone": "+91 44 2530 5000",
        "website": "https://www.mmc.ac.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0805&mlon=80.2785&zoom=15",
        "rating": 4.5,
        "hospital_type": "Government",
        "specialties": "General Medicine, Cardiology, Neurology, Nephrology, Trauma & Emergency, General Surgery",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 2723,
    },
    {
        "google_place_id": "tn_chennai_stanley",
        "hospital_name": "Government Stanley Medical College Hospital",
        "address": "Old Jail Road, Royapuram, Chennai, Tamil Nadu 600001",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.1075,
        "longitude": 80.2872,
        "phone": "+91 44 2528 1351",
        "website": "https://stanleymedicalcollege.ac.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.1075&mlon=80.2872&zoom=15",
        "rating": 4.4,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Plastic Surgery, Gastroenterology, Hepatology, General Medicine, Pediatrics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 1280,
    },
    {
        "google_place_id": "tn_chennai_kilpauk",
        "hospital_name": "Government Kilpauk Medical College Hospital",
        "address": "822 Poonamallee High Road, Kilpauk, Chennai, Tamil Nadu 600010",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0784,
        "longitude": 80.2415,
        "phone": "+91 44 2836 4951",
        "website": "https://gkmc.ac.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0784&mlon=80.2415&zoom=15",
        "rating": 4.3,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Burns Unit, Plastic Surgery, Nephrology, General Medicine, Emergency Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 1050,
    },
    {
        "google_place_id": "tn_chennai_royapettah_gh",
        "hospital_name": "Government Royapettah Hospital",
        "address": "1 West Cott Road, Royapettah, Chennai, Tamil Nadu 600014",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0543,
        "longitude": 80.2612,
        "phone": "+91 44 2848 1111",
        "website": "https://www.tnhealth.tn.gov.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0543&mlon=80.2612&zoom=15",
        "rating": 4.2,
        "hospital_type": "Government",
        "specialties": "Surgical Oncology, Toxicology, General Medicine, Dermatology, Emergency Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 912,
    },
    {
        "google_place_id": "tn_chennai_ich_egmore",
        "hospital_name": "Institute of Child Health and Hospital for Children",
        "address": "Halls Road, Egmore, Chennai, Tamil Nadu 600008",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0756,
        "longitude": 80.2582,
        "phone": "+91 44 2819 1982",
        "website": "https://www.mmc.ac.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0756&mlon=80.2582&zoom=15",
        "rating": 4.5,
        "hospital_type": "Government",
        "specialties": "Pediatrics, Pediatric Surgery, Neonatology, Pediatric Cardiology, Pediatric Neurology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 837,
    },
    {
        "google_place_id": "tn_chennai_kgh_triplicane",
        "hospital_name": "Kasturba Gandhi Hospital for Women and Children",
        "address": "Police Commissioner Office Road, Triplicane, Chennai, Tamil Nadu 600005",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0645,
        "longitude": 80.2781,
        "phone": "+91 44 2844 4967",
        "website": "https://www.tnhealth.tn.gov.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0645&mlon=80.2781&zoom=15",
        "rating": 4.3,
        "hospital_type": "Government",
        "specialties": "Obstetrics, Gynecology, Neonatal Intensive Care, Maternal Health",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 550,
    },
    {
        "google_place_id": "tn_chennai_rio_egmore",
        "hospital_name": "Regional Institute of Ophthalmology and Government Ophthalmic Hospital",
        "address": "Rukmani Lakshmipathy Road, Egmore, Chennai, Tamil Nadu 600008",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0718,
        "longitude": 80.2604,
        "phone": "+91 44 2819 2811",
        "website": "https://www.tnhealth.tn.gov.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0718&mlon=80.2604&zoom=15",
        "rating": 4.4,
        "hospital_type": "Government",
        "specialties": "Ophthalmology, Cornea, Retina, Glaucoma, Pediatric Ophthalmology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 478,
    },
    {
        "google_place_id": "tn_chennai_tambaram_tb",
        "hospital_name": "Government Hospital of Thoracic Medicine",
        "address": "GST Road, Tambaram Sanatorium, Chennai, Tamil Nadu 600047",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9348,
        "longitude": 80.1287,
        "phone": "+91 44 2241 8450",
        "website": "https://www.ghtm.tn.gov.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9348&mlon=80.1287&zoom=15",
        "rating": 4.3,
        "hospital_type": "Government",
        "specialties": "Pulmonology, Thoracic Medicine, Tuberculosis Care, Respiratory Diseases",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 776,
    },
    {
        "google_place_id": "tn_chennai_kalaignar_centenary",
        "hospital_name": "Kalaignar Centenary Super Speciality Hospital (KCSSH)",
        "address": "Guindy, Chennai, Tamil Nadu 600032",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0102,
        "longitude": 80.2185,
        "phone": "+91 44 2250 0050",
        "website": "https://kcssh.tn.gov.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0102&mlon=80.2185&zoom=15",
        "rating": 4.6,
        "hospital_type": "Government",
        "specialties": "Cardiology, Cardio Thoracic Surgery, Neurology, Neurosurgery, Medical Oncology, Surgical Oncology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 1000,
    },

    # 2. Leading Private Multi-Specialty & Quaternary Hospitals
    {
        "google_place_id": "tn_chennai_apollo_greams",
        "hospital_name": "Apollo Hospitals Greams Road",
        "address": "21 Greams Lane, Off Greams Road, Thousand Lights, Chennai, Tamil Nadu 600006",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0592,
        "longitude": 80.2505,
        "phone": "+91 44 2829 0200",
        "website": "https://chennai.apollohospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0592&mlon=80.2505&zoom=15",
        "rating": 4.8,
        "hospital_type": "Private",
        "specialties": "Cardiology, Oncology, Neurology, Gastroenterology, Organ Transplant, Orthopedics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 600,
    },
    {
        "google_place_id": "tn_chennai_apollo_speciality_omr",
        "hospital_name": "Apollo Speciality Hospitals OMR",
        "address": "05/639 Old Mahabalipuram Road, Perungudi, Chennai, Tamil Nadu 600096",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9648,
        "longitude": 80.2443,
        "phone": "+91 44 2496 1111",
        "website": "https://chennai.apollohospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9648&mlon=80.2443&zoom=15",
        "rating": 4.7,
        "hospital_type": "Private",
        "specialties": "Emergency Care, Critical Care, Cardiology, Neurology, Orthopedics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 220,
    },
    {
        "google_place_id": "tn_chennai_apollo_firstmed",
        "hospital_name": "Apollo First Med Hospitals",
        "address": "154 Poonamallee High Road, Kilpauk, Chennai, Tamil Nadu 600010",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0792,
        "longitude": 80.2441,
        "phone": "+91 44 2821 1111",
        "website": "https://chennai.apollohospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0792&mlon=80.2441&zoom=15",
        "rating": 4.6,
        "hospital_type": "Private",
        "specialties": "General Surgery, Cardiology, Internal Medicine, ENT, Orthopedics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 130,
    },
    {
        "google_place_id": "tn_chennai_apollo_proton",
        "hospital_name": "Apollo Proton Cancer Centre",
        "address": "100 Feet Road, Tharamani, Chennai, Tamil Nadu 600113",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9774,
        "longitude": 80.2392,
        "phone": "+91 44 3315 1111",
        "website": "https://proton.apollohospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9774&mlon=80.2392&zoom=15",
        "rating": 4.9,
        "hospital_type": "Private",
        "specialties": "Proton Beam Therapy, Radiation Oncology, Medical Oncology, Surgical Oncology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 150,
    },
    {
        "google_place_id": "tn_chennai_miot",
        "hospital_name": "MIOT International Hospital",
        "address": "4/112 Mount Poonamallee Road, Manapakkam, Chennai, Tamil Nadu 600089",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0225,
        "longitude": 80.1764,
        "phone": "+91 44 4200 2288",
        "website": "https://www.miotinternational.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0225&mlon=80.1764&zoom=15",
        "rating": 4.7,
        "hospital_type": "Private",
        "specialties": "Orthopedics, Joint Replacement, Trauma Care, Cardiology, Nephrology, Multi-Organ Transplant",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 1000,
    },
    {
        "google_place_id": "tn_chennai_sims",
        "hospital_name": "SIMS Hospital Vadapalani",
        "address": "1 Jawaharlal Nehru Salai, Vadapalani, Chennai, Tamil Nadu 600026",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0504,
        "longitude": 80.2121,
        "phone": "+91 44 4921 1455",
        "website": "https://simshospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0504&mlon=80.2121&zoom=15",
        "rating": 4.6,
        "hospital_type": "Private",
        "specialties": "Cardiology, Multi-Organ Transplant, Neurosciences, Orthopedics, Oncology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 345,
    },
    {
        "google_place_id": "tn_chennai_mgm_healthcare",
        "hospital_name": "MGM Healthcare Nelson Manickam Road",
        "address": "New No. 72 Old No. 54, Nelson Manickam Road, Aminjikarai, Chennai, Tamil Nadu 600029",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0722,
        "longitude": 80.2228,
        "phone": "+91 44 4524 2424",
        "website": "https://mgmhealthcare.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0722&mlon=80.2228&zoom=15",
        "rating": 4.8,
        "hospital_type": "Private",
        "specialties": "Heart & Lung Transplant, Cardiology, Neurosciences, Orthopedics, Critical Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 400,
    },
    {
        "google_place_id": "tn_chennai_gleneagles_global",
        "hospital_name": "Gleneagles BGS Global Health City",
        "address": "439 Cheran Nagar, Perumbakkam, Chennai, Tamil Nadu 600100",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9022,
        "longitude": 80.2036,
        "phone": "+91 44 4624 2424",
        "website": "https://gleneaglesglobalhealthcitychennai.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9022&mlon=80.2036&zoom=15",
        "rating": 4.6,
        "hospital_type": "Private",
        "specialties": "Liver Transplant, Kidney Transplant, Cardiology, Oncology, Pulmonology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 1000,
    },
    {
        "google_place_id": "tn_chennai_kauvery_alwarpet",
        "hospital_name": "Kauvery Hospital Alwarpet",
        "address": "199 Luz Church Road, Mylapore, Chennai, Tamil Nadu 600004",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0378,
        "longitude": 80.2605,
        "phone": "+91 44 4000 6000",
        "website": "https://kauveryhospital.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0378&mlon=80.2605&zoom=15",
        "rating": 4.7,
        "hospital_type": "Private",
        "specialties": "Cardiology, Geriatrics, Vascular Surgery, Orthopedics, Neurosciences, Emergency",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 200,
    },
    {
        "google_place_id": "tn_chennai_kauvery_vadapalani",
        "hospital_name": "Kauvery Hospital Vadapalani",
        "address": "23/1 Arcot Road, Vadapalani, Chennai, Tamil Nadu 600026",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0526,
        "longitude": 80.2091,
        "phone": "+91 44 4000 6000",
        "website": "https://kauveryhospital.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0526&mlon=80.2091&zoom=15",
        "rating": 4.7,
        "hospital_type": "Private",
        "specialties": "Cardiology, Oncology, Orthopedics, Gastroenterology, Emergency Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 250,
    },
    {
        "google_place_id": "tn_chennai_fortis_malar",
        "hospital_name": "Fortis Malar Hospital Adyar",
        "address": "52 1st Main Road, Gandhi Nagar, Adyar, Chennai, Tamil Nadu 600020",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0067,
        "longitude": 80.2572,
        "phone": "+91 44 4289 2222",
        "website": "https://www.fortishealthcare.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0067&mlon=80.2572&zoom=15",
        "rating": 4.5,
        "hospital_type": "Private",
        "specialties": "Cardiology, Cardiothoracic Surgery, Neurology, Nephrology, Emergency Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 180,
    },
    {
        "google_place_id": "tn_chennai_fortis_vadapalani",
        "hospital_name": "Fortis Hospital Vadapalani",
        "address": "Arulanandam Nagar, Vadapalani, Chennai, Tamil Nadu 600026",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0548,
        "longitude": 80.2107,
        "phone": "+91 44 4040 7777",
        "website": "https://www.fortishealthcare.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0548&mlon=80.2107&zoom=15",
        "rating": 4.6,
        "hospital_type": "Private",
        "specialties": "Cardiology, Pulmonology, Orthopedics, Oncology, Critical Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 250,
    },
    {
        "google_place_id": "tn_chennai_vijaya_hospital",
        "hospital_name": "Vijaya Multispeciality Hospital",
        "address": "434 N.S.K. Salai, Vadapalani, Chennai, Tamil Nadu 600026",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0518,
        "longitude": 80.2104,
        "phone": "+91 44 6664 6664",
        "website": "https://vijayahospital.org",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0518&mlon=80.2104&zoom=15",
        "rating": 4.5,
        "hospital_type": "Private",
        "specialties": "Cardiology, Orthopedics, Trauma, Neurology, Nephrology, General Surgery",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 750,
    },
    {
        "google_place_id": "tn_chennai_srmc_porur",
        "hospital_name": "Sri Ramachandra Institute of Higher Education and Research (SRMC)",
        "address": "No. 1 Ramachandra Nagar, Porur, Chennai, Tamil Nadu 600116",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0382,
        "longitude": 80.1428,
        "phone": "+91 44 4592 8500",
        "website": "https://www.sriramachandra.edu.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0382&mlon=80.1428&zoom=15",
        "rating": 4.7,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Cardiology, Oncology, Multi-Organ Transplant, Neurology, Pediatrics, Orthopedics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 1800,
    },
    {
        "google_place_id": "tn_chennai_rela_chromepet",
        "hospital_name": "Dr. Rela Institute & Medical Centre",
        "address": "7 CLC Works Road, Nagappa Nagar, Chromepet, Chennai, Tamil Nadu 600044",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9515,
        "longitude": 80.1408,
        "phone": "+91 44 6666 7777",
        "website": "https://www.relainstitute.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9515&mlon=80.1408&zoom=15",
        "rating": 4.8,
        "hospital_type": "Private",
        "specialties": "Liver Disease & Transplantation, Multi-Organ Transplant, Cardiology, Oncology, Pediatrics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 450,
    },
    {
        "google_place_id": "tn_chennai_smf_anna_nagar",
        "hospital_name": "Sundaram Medical Foundation (SMF)",
        "address": "9-C 4th Avenue, Shanthi Colony, Anna Nagar, Chennai, Tamil Nadu 600040",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0848,
        "longitude": 80.2081,
        "phone": "+91 44 2626 8844",
        "website": "https://www.smfindia.org",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0848&mlon=80.2081&zoom=15",
        "rating": 4.6,
        "hospital_type": "Trust / Non-Profit",
        "specialties": "Emergency Medicine, Critical Care, General Medicine, Pediatrics, Orthopedics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 200,
    },
    {
        "google_place_id": "tn_chennai_billroth_shenoy",
        "hospital_name": "Billroth Hospitals Shenoy Nagar",
        "address": "43 Lakshmi Talkies Road, Shenoy Nagar, Chennai, Tamil Nadu 600030",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0781,
        "longitude": 80.2291,
        "phone": "+91 44 2664 1777",
        "website": "https://billrothhospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0781&mlon=80.2291&zoom=15",
        "rating": 4.4,
        "hospital_type": "Private",
        "specialties": "Gastroenterology, Oncology, Cardiology, Orthopedics, Urology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 350,
    },
    {
        "google_place_id": "tn_chennai_billroth_ra_puram",
        "hospital_name": "Billroth Hospitals R.A. Puram",
        "address": "52 2nd Main Road, R.A. Puram, Chennai, Tamil Nadu 600028",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0289,
        "longitude": 80.2524,
        "phone": "+91 44 4292 1777",
        "website": "https://billrothhospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0289&mlon=80.2524&zoom=15",
        "rating": 4.3,
        "hospital_type": "Private",
        "specialties": "Internal Medicine, Cardiology, General Surgery, Gynecology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 100,
    },
    {
        "google_place_id": "tn_chennai_mehtas_chetpet",
        "hospital_name": "Dr. Mehta's Hospitals Chetpet",
        "address": "No. 2 Mc Nichols Road 3rd Lane, Chetpet, Chennai, Tamil Nadu 600031",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0697,
        "longitude": 80.2389,
        "phone": "+91 44 4227 1001",
        "website": "https://mehtahospital.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0697&mlon=80.2389&zoom=15",
        "rating": 4.5,
        "hospital_type": "Private",
        "specialties": "Pediatrics, Pediatric Surgery, Neonatology, Obstetrics & Gynecology, General Medicine",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 250,
    },
    {
        "google_place_id": "tn_chennai_mehtas_velachery",
        "hospital_name": "Dr. Mehta's Hospitals Velachery",
        "address": "Velachery Bypass Road, Velachery, Chennai, Tamil Nadu 600042",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9815,
        "longitude": 80.2198,
        "phone": "+91 44 4005 4005",
        "website": "https://mehtahospital.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9815&mlon=80.2198&zoom=15",
        "rating": 4.5,
        "hospital_type": "Private",
        "specialties": "Pediatrics, Emergency Care, Cardiology, Orthopedics, General Surgery",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 220,
    },
    {
        "google_place_id": "tn_chennai_prashanth_velachery",
        "hospital_name": "Prashanth Super Speciality Hospital Velachery",
        "address": "No. 36 & 36A Velachery Main Road, Velachery, Chennai, Tamil Nadu 600042",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9782,
        "longitude": 80.2186,
        "phone": "+91 44 4680 5555",
        "website": "https://prashanthhospital.org",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9782&mlon=80.2186&zoom=15",
        "rating": 4.4,
        "hospital_type": "Private",
        "specialties": "Cardiology, Urology, Reproductive Medicine, Orthopedics, Oncology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 300,
    },
    {
        "google_place_id": "tn_chennai_kamakshi_pallikaranai",
        "hospital_name": "Dr. Kamakshi Memorial Hospital",
        "address": "1 Radial Road, Dandeeswarar Nagar, Pallikaranai, Chennai, Tamil Nadu 600100",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9464,
        "longitude": 80.2015,
        "phone": "+91 44 6630 0300",
        "website": "https://www.drkmh.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9464&mlon=80.2015&zoom=15",
        "rating": 4.5,
        "hospital_type": "Private",
        "specialties": "Oncology, Cardiology, Vascular Surgery, Nephrology, Trauma Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 300,
    },
    {
        "google_place_id": "tn_chennai_mmm_mogappair",
        "hospital_name": "Madras Medical Mission (MMM)",
        "address": "4-A Dr. J. Jayalalitha Nagar, Mogappair East, Chennai, Tamil Nadu 600037",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0886,
        "longitude": 80.1882,
        "phone": "+91 44 2656 8000",
        "website": "https://www.madrasmedicalmission.org",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0886&mlon=80.1882&zoom=15",
        "rating": 4.7,
        "hospital_type": "Trust / Non-Profit",
        "specialties": "Adult & Pediatric Cardiology, Cardiac Surgery, Reproductive Medicine, Kidney Transplant",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 300,
    },
    {
        "google_place_id": "tn_chennai_frontier_lifeline",
        "hospital_name": "Frontier Lifeline Hospital (Dr. K.M. Cherian Heart Foundation)",
        "address": "R-30C Ambattur Industrial Estate Road, Mogappair, Chennai, Tamil Nadu 600101",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0905,
        "longitude": 80.1795,
        "phone": "+91 44 4201 7575",
        "website": "https://frontierlifeline.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0905&mlon=80.1795&zoom=15",
        "rating": 4.6,
        "hospital_type": "Private",
        "specialties": "Cardiothoracic Surgery, Pediatric Cardiology, Heart Failure Management, Electrophysiology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 120,
    },
    {
        "google_place_id": "tn_chennai_cancer_institute_adyar",
        "hospital_name": "Cancer Institute (WIA) Adyar",
        "address": "East Canal Bank Road, Gandhi Nagar, Adyar, Chennai, Tamil Nadu 600020",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0089,
        "longitude": 80.2486,
        "phone": "+91 44 2220 9150",
        "website": "https://cancerinstitutewia.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0089&mlon=80.2486&zoom=15",
        "rating": 4.8,
        "hospital_type": "Trust / Non-Profit",
        "specialties": "Medical Oncology, Surgical Oncology, Radiation Oncology, Pediatric Oncology, Palliative Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 550,
    },
    {
        "google_place_id": "tn_chennai_sankara_nethralaya_main",
        "hospital_name": "Sankara Nethralaya Main Hospital",
        "address": "No. 41 Old No. 18 College Road, Nungambakkam, Chennai, Tamil Nadu 600006",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0642,
        "longitude": 80.2464,
        "phone": "+91 44 4227 1500",
        "website": "https://www.sankaranethralaya.org",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0642&mlon=80.2464&zoom=15",
        "rating": 4.8,
        "hospital_type": "Trust / Non-Profit",
        "specialties": "Ophthalmology, Vitreo-Retina, Cornea, Glaucoma, Pediatric Ophthalmology, Ocular Oncology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 205,
    },
    {
        "google_place_id": "tn_chennai_vhs_taramani",
        "hospital_name": "Voluntary Health Services (VHS Hospital)",
        "address": "Rajiv Gandhi Salai, Taramani, Chennai, Tamil Nadu 600113",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9868,
        "longitude": 80.2458,
        "phone": "+91 44 2254 1972",
        "website": "https://vhschennai.org",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9868&mlon=80.2458&zoom=15",
        "rating": 4.4,
        "hospital_type": "Trust / Non-Profit",
        "specialties": "General Medicine, Neurosurgery, Hemophilia Care, Infectious Diseases, Pediatrics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 465,
    },
    {
        "google_place_id": "tn_chennai_hindu_mission_tambaram",
        "hospital_name": "Hindu Mission Hospital Tambaram",
        "address": "103 GST Road, West Tambaram, Chennai, Tamil Nadu 600045",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9238,
        "longitude": 80.1165,
        "phone": "+91 44 2226 2244",
        "website": "https://hindumissionhospital.org",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9238&mlon=80.1165&zoom=15",
        "rating": 4.5,
        "hospital_type": "Trust / Non-Profit",
        "specialties": "Cardiology, Nephrology, Dialysis, Orthopedics, Ophthalmology, Critical Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 300,
    },
    {
        "google_place_id": "tn_chennai_csi_kalyani",
        "hospital_name": "CSI Kalyani General Hospital",
        "address": "15 Edward Elliots Road, Radhakrishnan Salai, Mylapore, Chennai, Tamil Nadu 600004",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0441,
        "longitude": 80.2642,
        "phone": "+91 44 2847 4300",
        "website": "https://csikalyanihospital.org",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0441&mlon=80.2642&zoom=15",
        "rating": 4.3,
        "hospital_type": "Trust / Non-Profit",
        "specialties": "Obstetrics & Gynecology, Pediatrics, General Surgery, Internal Medicine",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 220,
    },
    {
        "google_place_id": "tn_chennai_st_isabels",
        "hospital_name": "St. Isabel's Hospital Mylapore",
        "address": "49 Oliver Road, Mylapore, Chennai, Tamil Nadu 600004",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0335,
        "longitude": 80.2618,
        "phone": "+91 44 2499 1081",
        "website": "https://stisabelshospital.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0335&mlon=80.2618&zoom=15",
        "rating": 4.4,
        "hospital_type": "Trust / Non-Profit",
        "specialties": "General Medicine, Obstetrics, Pediatrics, Orthopedics, ENT, Ophthalmology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 300,
    },
    {
        "google_place_id": "tn_chennai_chettinad_health_city",
        "hospital_name": "Chettinad Super Speciality Hospital (Chettinad Health City)",
        "address": "Rajiv Gandhi Salai, Kelambakkam, Chennai, Tamil Nadu 603103",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.7915,
        "longitude": 80.2212,
        "phone": "+91 44 4741 1000",
        "website": "https://chettinadhealthcity.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.7915&mlon=80.2212&zoom=15",
        "rating": 4.6,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Cardiology, Multi-Organ Transplant, Oncology, Neurosciences, Emergency & Trauma",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 1180,
    },
    {
        "google_place_id": "tn_chennai_srm_kattankulathur",
        "hospital_name": "SRM Medical College Hospital & Research Centre",
        "address": "GST Road, Kattankulathur, Chennai, Tamil Nadu 603203",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.8231,
        "longitude": 80.0442,
        "phone": "+91 44 4743 2333",
        "website": "https://www.srmist.edu.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.8231&mlon=80.0442&zoom=15",
        "rating": 4.5,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Cardiology, Nephrology, Neurology, General Surgery, Orthopedics, Trauma Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 1210,
    },
    {
        "google_place_id": "tn_chennai_saveetha_thandalam",
        "hospital_name": "Saveetha Medical College and Hospital",
        "address": "Saveetha Nagar, Thandalam, Chennai, Tamil Nadu 602105",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0281,
        "longitude": 80.0152,
        "phone": "+91 44 6672 6672",
        "website": "https://saveethamedicalcollege.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0281&mlon=80.0152&zoom=15",
        "rating": 4.5,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Cardiology, Urology, Orthopedics, Critical Care, Trauma & Emergency",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 1100,
    },
    {
        "google_place_id": "tn_chennai_acs_medical_college",
        "hospital_name": "ACS Medical College and Hospital",
        "address": "Poonamallee High Road, Velappanchavadi, Chennai, Tamil Nadu 600077",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0564,
        "longitude": 80.1341,
        "phone": "+91 44 2680 1550",
        "website": "https://acsmch.ac.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0564&mlon=80.1341&zoom=15",
        "rating": 4.3,
        "hospital_type": "Teaching / Medical College",
        "specialties": "General Medicine, General Surgery, Obstetrics & Gynecology, Pediatrics, Orthopedics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 700,
    },
    {
        "google_place_id": "tn_chennai_tagore_medical",
        "hospital_name": "Tagore Medical College and Hospital",
        "address": "Rathinamangalam, Vandalur, Chennai, Tamil Nadu 600127",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.8724,
        "longitude": 80.1448,
        "phone": "+91 44 3010 1111",
        "website": "https://tagoremch.edu.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.8724&mlon=80.1448&zoom=15",
        "rating": 4.3,
        "hospital_type": "Teaching / Medical College",
        "specialties": "General Medicine, Orthopedics, Pediatrics, OB-GYN, Ophthalmology, Emergency",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 500,
    },
    {
        "google_place_id": "tn_chennai_balaji_chromepet",
        "hospital_name": "Sree Balaji Medical College & Hospital",
        "address": "7 Works Road, Chromepet, Chennai, Tamil Nadu 600044",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9538,
        "longitude": 80.1432,
        "phone": "+91 44 2241 5603",
        "website": "https://sbmch.ac.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9538&mlon=80.1432&zoom=15",
        "rating": 4.4,
        "hospital_type": "Teaching / Medical College",
        "specialties": "Cardiology, Neurology, Nephrology, General Medicine, Trauma Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 1050,
    },
    {
        "google_place_id": "tn_chennai_dr_agarwals_cathedral",
        "hospital_name": "Dr. Agarwal's Eye Hospital Cathedral Road",
        "address": "19 Cathedral Road, Gopalapuram, Chennai, Tamil Nadu 600086",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0489,
        "longitude": 80.2525,
        "phone": "+91 44 4300 8800",
        "website": "https://www.dragarwal.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0489&mlon=80.2525&zoom=15",
        "rating": 4.7,
        "hospital_type": "Private",
        "specialties": "Ophthalmology, Cataract Surgery, Refractive Surgery, Glaucoma, Cornea, Retina",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 80,
    },
    {
        "google_place_id": "tn_chennai_rainbow_guindy",
        "hospital_name": "Rainbow Children's Hospital Guindy",
        "address": "No. 157 Anna Salai, Guindy, Chennai, Tamil Nadu 600032",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0118,
        "longitude": 80.2195,
        "phone": "+91 44 4012 3456",
        "website": "https://www.rainbowhospitals.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0118&mlon=80.2195&zoom=15",
        "rating": 4.8,
        "hospital_type": "Private",
        "specialties": "Pediatric Intensive Care (PICU), Neonatal Intensive Care (NICU), Pediatric Surgery, Perinatology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 150,
    },
    {
        "google_place_id": "tn_chennai_rainbow_sholinganallur",
        "hospital_name": "Rainbow Children's Hospital Sholinganallur",
        "address": "OMR Sholinganallur Junction, Chennai, Tamil Nadu 600119",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.8988,
        "longitude": 80.2285,
        "phone": "+91 44 4012 3456",
        "website": "https://www.rainbowhospitals.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.8988&mlon=80.2285&zoom=15",
        "rating": 4.7,
        "hospital_type": "Private",
        "specialties": "Pediatrics, Pediatric Cardiology, Neonatology, Obstetrics, Gynecology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 100,
    },
    {
        "google_place_id": "tn_chennai_cloudnine_tnagar",
        "hospital_name": "Cloudnine Hospital T. Nagar",
        "address": "No. 54 Vijaya Raghava Road, T. Nagar, Chennai, Tamil Nadu 600017",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0415,
        "longitude": 80.2398,
        "phone": "+91 99728 99728",
        "website": "https://www.cloudninecare.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0415&mlon=80.2398&zoom=15",
        "rating": 4.7,
        "hospital_type": "Private",
        "specialties": "Maternity, Obstetrics & Gynecology, Neonatology, Fertility, Pediatrics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 75,
    },
    {
        "google_place_id": "tn_chennai_motherhood_alwarpet",
        "hospital_name": "Motherhood Hospital Alwarpet",
        "address": "542 TTK Road, Alwarpet, Chennai, Tamil Nadu 600018",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0362,
        "longitude": 80.2514,
        "phone": "+91 84949 08494",
        "website": "https://www.motherhoodindia.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0362&mlon=80.2514&zoom=15",
        "rating": 4.6,
        "hospital_type": "Private",
        "specialties": "Pregnancy & Delivery, Advanced Laparoscopy, Neonatal Care, Infertility Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 65,
    },
    {
        "google_place_id": "tn_chennai_soundarapandian_bone",
        "hospital_name": "Soundarapandian Bone and Joint Hospital",
        "address": "AA-16 3rd Main Road, Anna Nagar, Chennai, Tamil Nadu 600040",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0864,
        "longitude": 80.2132,
        "phone": "+91 44 4206 6666",
        "website": "https://soundarapandian.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0864&mlon=80.2132&zoom=15",
        "rating": 4.6,
        "hospital_type": "Private",
        "specialties": "Orthopedic Surgery, Joint Replacement, Spine Surgery, Arthroscopy, Trauma",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 70,
    },
    {
        "google_place_id": "tn_chennai_medway_kodambakkam",
        "hospital_name": "Medway Hospitals Kodambakkam",
        "address": "33/3 United India Colony 1st Main Road, Kodambakkam, Chennai, Tamil Nadu 600024",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0538,
        "longitude": 80.2245,
        "phone": "+91 44 4004 4004",
        "website": "https://medwayhospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0538&mlon=80.2245&zoom=15",
        "rating": 4.5,
        "hospital_type": "Private",
        "specialties": "Cardiology, Urology, Critical Care, Nephrology, Gastroenterology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 100,
    },
    {
        "google_place_id": "tn_chennai_bewell_tnagar",
        "hospital_name": "Be Well Hospitals T. Nagar",
        "address": "No. 1 Vijaya Raghava Road, T. Nagar, Chennai, Tamil Nadu 600017",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0428,
        "longitude": 80.2412,
        "phone": "+91 44 4344 0440",
        "website": "https://www.bewellhospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0428&mlon=80.2412&zoom=15",
        "rating": 4.4,
        "hospital_type": "Private",
        "specialties": "Emergency Care, General Surgery, Orthopedics, Cardiology, Pediatrics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 50,
    },
    {
        "google_place_id": "tn_chennai_bewell_annanagar",
        "hospital_name": "Be Well Hospitals Anna Nagar",
        "address": "Plot No. 1629 16th Main Road, Anna Nagar, Chennai, Tamil Nadu 600040",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0878,
        "longitude": 80.2104,
        "phone": "+91 44 4344 0440",
        "website": "https://www.bewellhospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0878&mlon=80.2104&zoom=15",
        "rating": 4.4,
        "hospital_type": "Private",
        "specialties": "General Medicine, General Surgery, Orthopedics, Emergency Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 50,
    },
    {
        "google_place_id": "tn_chennai_bewell_kilpauk",
        "hospital_name": "Be Well Hospitals Kilpauk",
        "address": "No. 2 Balfour Road, Kilpauk, Chennai, Tamil Nadu 600010",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0788,
        "longitude": 80.2375,
        "phone": "+91 44 4344 0440",
        "website": "https://www.bewellhospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0788&mlon=80.2375&zoom=15",
        "rating": 4.4,
        "hospital_type": "Private",
        "specialties": "Emergency Medicine, Critical Care, Multispeciality Surgery",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 45,
    },
    {
        "google_place_id": "tn_chennai_bewell_ambattur",
        "hospital_name": "Be Well Hospitals Ambattur",
        "address": "MTH Road, Sidco Industrial Estate, Ambattur, Chennai, Tamil Nadu 600058",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.1142,
        "longitude": 80.1558,
        "phone": "+91 44 4344 0440",
        "website": "https://www.bewellhospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.1142&mlon=80.1558&zoom=15",
        "rating": 4.3,
        "hospital_type": "Private",
        "specialties": "Trauma, Emergency, Occupational Health, General Surgery",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 50,
    },
    {
        "google_place_id": "tn_chennai_bewell_poonamallee",
        "hospital_name": "Be Well Hospitals Poonamallee",
        "address": "Trunk Road, Poonamallee, Chennai, Tamil Nadu 600056",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0485,
        "longitude": 80.1082,
        "phone": "+91 44 4344 0440",
        "website": "https://www.bewellhospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0485&mlon=80.1082&zoom=15",
        "rating": 4.3,
        "hospital_type": "Private",
        "specialties": "Emergency Care, Orthopedics, General Medicine, Pediatrics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 50,
    },
    {
        "google_place_id": "tn_chennai_vs_hospitals_chetpet",
        "hospital_name": "VS Hospitals Advanced Cancer Care Chetpet",
        "address": "13 East Spurtank Road, Chetpet, Chennai, Tamil Nadu 600031",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0678,
        "longitude": 80.2425,
        "phone": "+91 44 4000 6666",
        "website": "https://vshospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0678&mlon=80.2425&zoom=15",
        "rating": 4.6,
        "hospital_type": "Private",
        "specialties": "Comprehensive Oncology, Surgical Oncology, Medical Oncology, Radiation Therapy",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 100,
    },
    {
        "google_place_id": "tn_chennai_vs_hospitals_kilpauk",
        "hospital_name": "VS Hospitals Kilpauk",
        "address": "815 Poonamallee High Road, Kilpauk, Chennai, Tamil Nadu 600010",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0782,
        "longitude": 80.2431,
        "phone": "+91 44 4000 6666",
        "website": "https://vshospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0782&mlon=80.2431&zoom=15",
        "rating": 4.5,
        "hospital_type": "Private",
        "specialties": "Multispeciality Care, Geriatric Care, General Surgery, Internal Medicine",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 80,
    },
    {
        "google_place_id": "tn_chennai_kumaran_kilpauk",
        "hospital_name": "Kumaran Hospitals Kilpauk",
        "address": "214 E.V.R. Periyar Salai, Poonamallee High Road, Kilpauk, Chennai, Tamil Nadu 600010",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0798,
        "longitude": 80.2482,
        "phone": "+91 44 2641 2232",
        "website": "https://kumaranhospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0798&mlon=80.2482&zoom=15",
        "rating": 4.4,
        "hospital_type": "Private",
        "specialties": "Cardiology, Gastroenterology, Nephrology, Urology, Laparoscopic Surgery",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 120,
    },
    {
        "google_place_id": "tn_chennai_sooriya_saligramam",
        "hospital_name": "Sooriya Hospital Saligramam",
        "address": "No. 1 Arunachalam Road, Saligramam, Chennai, Tamil Nadu 600093",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0521,
        "longitude": 80.1985,
        "phone": "+91 44 2376 1750",
        "website": "https://sooriyahospital.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0521&mlon=80.1985&zoom=15",
        "rating": 4.4,
        "hospital_type": "Private",
        "specialties": "Cardiology, Obstetrics & Gynecology, Pediatrics, Nephrology, Orthopedics",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 200,
    },
    {
        "google_place_id": "tn_chennai_parvathy_chromepet",
        "hospital_name": "Parvathy Hospital Chromepet",
        "address": "No. 241 GST Road, Chromepet, Chennai, Tamil Nadu 600044",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9512,
        "longitude": 80.1415,
        "phone": "+91 44 2238 2244",
        "website": "https://parvathyhospital.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9512&mlon=80.1415&zoom=15",
        "rating": 4.5,
        "hospital_type": "Private",
        "specialties": "Orthopedics, Joint Replacement, Neuro & Spine Surgery, Trauma Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 150,
    },
    {
        "google_place_id": "tn_chennai_deepam_tambaram",
        "hospital_name": "Deepam Hospitals Tambaram",
        "address": "No. 107 GST Road, West Tambaram, Chennai, Tamil Nadu 600045",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9245,
        "longitude": 80.1172,
        "phone": "+91 44 2226 5252",
        "website": "https://deepamhospitals.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9245&mlon=80.1172&zoom=15",
        "rating": 4.3,
        "hospital_type": "Private",
        "specialties": "Emergency Care, General Medicine, Cardiology, Orthopedics, Urology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 100,
    },
    {
        "google_place_id": "tn_chennai_kauvery_radial_road",
        "hospital_name": "Kauvery Hospital Radial Road",
        "address": "2/1 Kovilambakkam, Radial Road, Chennai, Tamil Nadu 600129",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9392,
        "longitude": 80.1885,
        "phone": "+91 44 4000 6000",
        "website": "https://kauveryhospital.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9392&mlon=80.1885&zoom=15",
        "rating": 4.7,
        "hospital_type": "Private",
        "specialties": "Cardiology, Oncology, Neurosciences, Orthopedics, Organ Transplant",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 250,
    },
    {
        "google_place_id": "tn_chennai_mgm_cancer_aminjikarai",
        "hospital_name": "MGM Cancer Institute Aminjikarai",
        "address": "Nelson Manickam Road, Aminjikarai, Chennai, Tamil Nadu 600029",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0728,
        "longitude": 80.2232,
        "phone": "+91 44 4524 2424",
        "website": "https://mgmhealthcare.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0728&mlon=80.2232&zoom=15",
        "rating": 4.8,
        "hospital_type": "Private",
        "specialties": "Comprehensive Oncology, Bone Marrow Transplant, Medical, Surgical & Radiation Oncology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 150,
    },
    {
        "google_place_id": "tn_chennai_apollo_spectra_alwarpet",
        "hospital_name": "Apollo Spectra Hospitals Alwarpet",
        "address": "12 C.P. Ramaswamy Road, Alwarpet, Chennai, Tamil Nadu 600018",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0338,
        "longitude": 80.2522,
        "phone": "+91 44 6686 2000",
        "website": "https://www.apollospectra.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0338&mlon=80.2522&zoom=15",
        "rating": 4.6,
        "hospital_type": "Private",
        "specialties": "Short Stay Surgeries, Orthopedics, ENT, General Surgery, Gynecology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 45,
    },
    {
        "google_place_id": "tn_chennai_apollo_spectra_mrc_nagar",
        "hospital_name": "Apollo Spectra Hospitals MRC Nagar",
        "address": "41/42 Satyadev Avenue, MRC Nagar, R.A. Puram, Chennai, Tamil Nadu 600028",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0195,
        "longitude": 80.2742,
        "phone": "+91 44 6686 2000",
        "website": "https://www.apollospectra.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0195&mlon=80.2742&zoom=15",
        "rating": 4.6,
        "hospital_type": "Private",
        "specialties": "Minimally Invasive Surgery, Urology, Orthopedics, Spine Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 45,
    },
    {
        "google_place_id": "tn_chennai_bharathirajaa_tnagar",
        "hospital_name": "Bharathirajaa Speciality Hospital T. Nagar",
        "address": "45/1 G.N. Chetty Road, T. Nagar, Chennai, Tamil Nadu 600017",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0448,
        "longitude": 80.2395,
        "phone": "+91 44 4299 9999",
        "website": "https://bharathirajaahospital.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0448&mlon=80.2395&zoom=15",
        "rating": 4.3,
        "hospital_type": "Private",
        "specialties": "Cardiology, Urology, Orthopedics, Gynecology, Emergency",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 100,
    },
    {
        "google_place_id": "tn_chennai_noble_purasawalkam",
        "hospital_name": "Noble Hospital Purasawalkam",
        "address": "No. 11 Audiappa Street, Purasawalkam, Chennai, Tamil Nadu 600084",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0882,
        "longitude": 80.2584,
        "phone": "+91 44 2642 0011",
        "website": "https://noblehospitalschennai.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0882&mlon=80.2584&zoom=15",
        "rating": 4.2,
        "hospital_type": "Private",
        "specialties": "General Medicine, General Surgery, Orthopedics, Emergency Care",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 60,
    },
    {
        "google_place_id": "tn_chennai_hande_shenoy",
        "hospital_name": "Hande Hospital Shenoy Nagar",
        "address": "44 Lakshmi Talkies Road, Shenoy Nagar, Chennai, Tamil Nadu 600030",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0778,
        "longitude": 80.2285,
        "phone": "+91 44 2664 4525",
        "website": "https://handehospital.org",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0778&mlon=80.2285&zoom=15",
        "rating": 4.3,
        "hospital_type": "Private",
        "specialties": "General Surgery, Laparoscopy, Plastic Surgery, Urology",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 50,
    },
    {
        "google_place_id": "tn_chennai_astra_omr",
        "hospital_name": "Astra Speciality Hospital OMR",
        "address": "No. 129 OMR, Thoraipakkam, Chennai, Tamil Nadu 600097",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9362,
        "longitude": 80.2312,
        "phone": "+91 44 4040 0000",
        "website": "https://astrahospital.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9362&mlon=80.2312&zoom=15",
        "rating": 4.4,
        "hospital_type": "Private",
        "specialties": "Emergency Care, Cardiology, Orthopedics, Pediatrics, General Medicine",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 75,
    },
    {
        "google_place_id": "tn_chennai_trinity_alwarpet",
        "hospital_name": "Trinity Acute Care Hospital",
        "address": "No. 3/1 T.T.K. Road 1st Cross Street, Alwarpet, Chennai, Tamil Nadu 600018",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0395,
        "longitude": 80.2531,
        "phone": "+91 44 4353 3333",
        "website": "https://trinityhospital.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=13.0395&mlon=80.2531&zoom=15",
        "rating": 4.3,
        "hospital_type": "Private",
        "specialties": "Acute Care, Cardiology, Dialysis, General Medicine",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 60,
    },
    {
        "google_place_id": "tn_chennai_apollo_cradle_karapakkam",
        "hospital_name": "Apollo Cradle & Children's Hospital Karapakkam",
        "address": "OMR Karapakkam, Chennai, Tamil Nadu 600097",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9158,
        "longitude": 80.2295,
        "phone": "+91 44 4424 4424",
        "website": "https://www.apollocradle.com",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9158&mlon=80.2295&zoom=15",
        "rating": 4.7,
        "hospital_type": "Private",
        "specialties": "Maternity, Neonatology, Pediatrics, Gynecology, Fetal Medicine",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 60,
    },
    {
        "google_place_id": "tn_chennai_bloom_velachery",
        "hospital_name": "Bloom Healthcare Speciality Hospital Velachery",
        "address": "100 Feet Bypass Road, Velachery, Chennai, Tamil Nadu 600042",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 12.9802,
        "longitude": 80.2174,
        "phone": "+91 44 4000 0044",
        "website": "https://bloomhealthcare.in",
        "google_maps_url": "https://www.openstreetmap.org/?mlat=12.9802&mlon=80.2174&zoom=15",
        "rating": 4.5,
        "hospital_type": "Private",
        "specialties": "Fertility, Women & Child Health, Laparoscopy, General Surgery",
        "has_emergency_room": True,
        "opening_hours": "24/7",
        "beds": 50,
    },
]


async def seed_chennai_hospitals():
    print(f"[*] Seeding/Updating {len(CHENNAI_HOSPITALS)} curated Chennai hospitals...")
    async with AsyncSessionLocal() as session:
        inserted = 0
        updated = 0
        
        for h_data in CHENNAI_HOSPITALS:
            stmt = select(Hospital).where(Hospital.google_place_id == h_data["google_place_id"])
            res = await session.execute(stmt)
            existing_list = list(res.scalars().all())

            if not existing_list:
                # Also check by exact hospital name
                stmt_name = select(Hospital).where(Hospital.hospital_name == h_data["hospital_name"])
                res_name = await session.execute(stmt_name)
                existing_list = list(res_name.scalars().all())

            if existing_list:
                existing = existing_list[0]
                # If there were multiple duplicates in the DB, clean up the duplicate entries safely
                if len(existing_list) > 1:
                    for dup in existing_list[1:]:
                        await session.delete(dup)
                
                # Update fields to ensure verified data
                existing.google_place_id = h_data["google_place_id"]
                existing.hospital_name = h_data["hospital_name"]
                existing.address = h_data["address"]
                existing.city = h_data["city"]
                existing.state = h_data["state"]
                existing.latitude = h_data["latitude"]
                existing.longitude = h_data["longitude"]
                existing.phone = h_data["phone"]
                existing.website = h_data["website"]
                existing.google_maps_url = h_data["google_maps_url"]
                existing.rating = h_data["rating"]
                existing.hospital_type = h_data["hospital_type"]
                existing.specialties = h_data["specialties"]
                existing.has_emergency_room = h_data["has_emergency_room"]
                existing.opening_hours = h_data["opening_hours"]
                existing.beds = h_data["beds"]
            else:
                new_hosp = Hospital(**h_data)
                session.add(new_hosp)
                inserted += 1

        await session.commit()
        print(f"[+] Done. Inserted: {inserted}, Updated: {updated}, Total: {inserted + updated}")

        # Verify count
        total_stmt = select(Hospital)
        res_total = await session.execute(total_stmt)
        all_h = res_total.scalars().all()
        chennai_h = [h for h in all_h if h.city == "Chennai"]
        print(f"[+] Total Hospitals in DB: {len(all_h)} (Chennai Hospitals: {len(chennai_h)})")


if __name__ == "__main__":
    asyncio.run(seed_chennai_hospitals())
