"use client";

import React, { useState, useEffect } from "react";
import { HealthTip, HealthTipCategory } from "@/types/healthTip";
import { healthTipApi } from "@/lib/mockHealthTipData";
import { HealthTipCard } from "@/components/health-tips/HealthTipCard";
import { HealthTipFilterChips } from "@/components/health-tips/HealthTipFilterChips";
import { Spinner } from "@/components/ui/Spinner";
import { Card } from "@/components/ui/Card";
import { Sparkles, AlertTriangle, Info } from "lucide-react";
import { useLanguage } from "@/context/LanguageContext";

export default function TipsPage() {
  const [tips, setTips] = useState<HealthTip[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedCategory, setSelectedCategory] = useState<HealthTipCategory | "All">("All");
  const { t, language } = useLanguage();

  useEffect(() => {
    const fetchTips = async () => {
      setLoading(true);
      try {
        const data = await healthTipApi.getTips(selectedCategory, true);
        setTips(data);
      } catch (err) {
        console.error("Failed to load health tips", err);
      } finally {
        setLoading(false);
      }
    };

    fetchTips();
  }, [selectedCategory]);

  return (
    <div className="flex flex-col gap-6 max-w-5xl mx-auto py-2">
      {/* Page Header */}
      <div className="border-b border-[#F0FDFA] pb-4">
        <div className="flex items-center gap-3 mb-1">
          <div className="w-9 h-9 rounded-xl bg-emerald-600 text-white flex items-center justify-center">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h1 className="font-heading text-2xl sm:text-3xl font-bold text-[#0F172A] tracking-tight">
              {t.healthTipsTitle}
            </h1>
            <p className="text-xs sm:text-sm text-[#64748B] mt-1">
              {t.healthTipsSub}
            </p>
          </div>
        </div>
      </div>

      {/* Phase 1: Non-diagnostic disclaimer — clearly distinguishes general guidance */}
      <Card className="border border-amber-200 bg-amber-50/60 p-4 flex flex-col gap-2">
        <div className="flex items-start gap-2">
          <AlertTriangle className="w-4 h-4 text-amber-600 mt-0.5 shrink-0" />
          <div>
            <p className="text-sm font-bold text-amber-800">{t.medicalDisclaimer}</p>
            <p className="text-xs text-amber-700 leading-relaxed mt-0.5">
              {t.medicalDisclaimerDesc}
            </p>
          </div>
        </div>
      </Card>

      {/* AI Generation Info */}
      <div className="flex items-center gap-2 text-xs text-slate-500 bg-slate-50 border border-slate-200 rounded-xl px-3 py-2">
        <Info className="w-3.5 h-3.5 shrink-0 text-slate-400" />
        <span>
          {language === "ta"
            ? "இந்த சுகாதார குறிப்புகள் Gemini 2.5 Flash மூலம் உருவாக்கப்பட்டு பொது ஆரோக்கியம் மற்றும் நோய் தடுப்புக்கு மட்டுமே கட்டுப்படுத்தப்பட்டுள்ளது."
            : "These tips are generated by Gemini 2.5 Flash and restricted to general preventive healthcare, seasonal wellness, nutrition, and chronic condition management guidance."}
        </span>
      </div>

      {/* Filter Chips */}
      <HealthTipFilterChips
        selectedCategory={selectedCategory}
        onSelectCategory={setSelectedCategory}
      />

      {/* Tips Grid */}
      {loading ? (
        <div className="flex flex-col items-center justify-center p-12 min-h-[300px]">
          <Spinner size="lg" color="primary" />
          <span className="text-xs text-[#64748B] mt-2">Loading health tips...</span>
        </div>
      ) : tips.length === 0 ? (
        <Card className="flex flex-col items-center gap-3 p-12 text-center border-dashed">
          <Sparkles className="w-10 h-10 text-slate-300" />
          <p className="text-sm font-semibold text-slate-500">No tips found for this filter</p>
          <button
            onClick={() => setSelectedCategory("All")}
            className="text-xs font-semibold text-teal-600 hover:underline"
          >
            View all tips
          </button>
        </Card>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {tips.map((tip) => (
            <HealthTipCard key={tip.tip_id} tip={tip} />
          ))}
        </div>
      )}

      {/* Escalation Guidance */}
      <Card className="border border-red-100 bg-red-50/40 p-4 flex flex-col gap-2">
        <div className="flex items-start gap-2">
          <AlertTriangle className="w-4 h-4 text-red-600 mt-0.5 shrink-0" />
          <div>
            <p className="text-sm font-bold text-red-800">
              {language === "ta" ? "எப்போது அவசர மருத்துவ சிகிச்சை பெற வேண்டும்?" : "When to Seek Emergency Care"}
            </p>
            <p className="text-xs text-red-700 leading-relaxed mt-0.5">
              {language === "ta"
                ? "நெஞ்சு வலி, மூச்சுத்திணறல், திடீர் கடுமையான தலைவலி அல்லது பக்கவாத அறிகுறிகள் இருந்தால் உடனடியாக 108 ஐ அழைக்கவும் அல்லது அருகில் உள்ள அவசர சிகிச்சை மையத்திற்கு செல்லவும்."
                : "If you experience chest pain, difficulty breathing, sudden severe headache, or loss of consciousness, call 108 immediately."}
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}
